### ISSUE TITLE
Hide previous github actions comments to reduce GitHub noise

### ISSUE THREAD

**Issue by OmarIthawi** [appsembler/action-conflict-counter#12]
### Using an action

```yaml
jobs:
  hide:
    steps:
      - uses: int128/hide-comment-action@5f4b3b8e995d6c0213dbd47bbfc54374839a2ae8   # @v1 on Jan 18th, 2022
        with:
          ends-with: '<!--- action-conflict-counter --->'
```

### Manual solution

1. List previous comments:

 - GH docs: https://docs.github.com/en/rest/reference/issues#list-issue-comments
 - Rest client docs: https://octokit.github.io/rest.js/v18#issues-list-comments

```js
github.rest.issues.listComments({
  owner,
  repo,
  issue_number,
});
```

2. for each comment from github actions with `<!--- action-conflict-counter --->` comment hide it.

 - GH docs: https://docs.github.com/en/rest/reference/issues#update-an-issue-comment
 - Rest client docs: https://octokit.github.io/rest.js/v18#issues-update-comment

```js
octokit.rest.issues.updateComment({
  owner,
  repo,
  comment_id,
  body,
});
```
